name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - '**.md'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: ['2.5', '2.6', '2.7', '3.0', '3.1', '3.2', '3.3']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@c4e5b1316158f92e3d49443a9d58b31d25ac0f8f # v1.306.0
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Generate Gemfile.lock
        run: bundle lock --lockfile=Gemfile.lock
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: vendor/bundle
          key: bundle-use-ruby-${{ matrix.os }}-${{ matrix.ruby }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            bundle-use-ruby-${{ matrix.os }}-${{ matrix.ruby }}-
      - run: bundle check --path .bundle || bundle install --path .bundle
      - name: MiniTest
        run: bundle exec rake no_slow_test
        timeout-minutes: 5

  slow_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: ['2.5', '2.6', '2.7', '3.0', '3.1', '3.2', '3.3']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@c4e5b1316158f92e3d49443a9d58b31d25ac0f8f # v1.306.0
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Generate Gemfile.lock
        run: bundle lock --lockfile=Gemfile.lock
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: vendor/bundle
          key: bundle-use-ruby-${{ matrix.os }}-${{ matrix.ruby }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            bundle-use-ruby-${{ matrix.os }}-${{ matrix.ruby }}-
      - run: bundle check --path .bundle || bundle install --path .bundle
      - name: MiniTest
        run: |
            TESTFILES=$(ls -d test/jct/slow_test/*)
            bundle exec ruby -e "%w[$TESTFILES].each { |test_file| load test_file }"
        timeout-minutes: 60
